server:
  port: 0

spring:
  application:
    name: ms-pedidos
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/alurafood-pedido?createDatabaseIfNotExist=true}
    username: root
    password: root
    jpa:
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms,100ms,200ms,300ms,500ms,1s
    tags:
      application: ms-pedidos