{
 "title": "dash-pedidos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "alurafood basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JDBC Pool",
   "type": "stat",
   "description": "Pool de conexões JDBC",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\",  job=\"prometheus-pedidos\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB connection  timeout",
   "type": "stat",
   "description": "conexões com database em timeout",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\",  instance=\"$instance\", job=\"$job\", pool=\"$pool\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Hora da inicialização",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\",instance=\"$instance\", job=\"prometheus-pedidos\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "API uptime",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"prometheus-pedidos\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Status",
   "type": "timeseries",
   "description": "nos últimos 5 minutos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) /sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) /sum(increase(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) /sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\", status=\"200\"}[5m])) /sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\", status=\"201\"}[5m])) /sum(rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"$job\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "201"
    }
   ]
  },
  {
   "title": "Warning e Error logs",
   "type": "timeseries",
   "description": "Warnings e errors logados nos últimos 5 minutos",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"prometheus-pedidos\", level=\"warn\"}[5m]))",
     "legendFormat": "warn"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"prometheus-pedidos\", level=\"error\"}[5m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "timeseries",
   "description": "Estado das conexões com o database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"$job\", pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"$job\", pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"$job\", pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Busca de pedidos por id",
   "type": "stat",
   "description": "pedidos encontrados e pedidos não encontrados",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pedido_encontrado_total[10m])",
     "legendFormat": "encontrados"
    },
    {
     "expr": "increase(pedido_nao_encontrado_total[10m])",
     "legendFormat": "nao encontrado"
    }
   ]
  },
  { "title": "Alurafood RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Req/seg",
   "type": "stat",
   "description": "Número de requisições no ultimo miniuto",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "Número de requisições por endpoint no último minuto",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\",uri=\"/pedidos/{id}\"}[1m]))",
     "legendFormat": "pedidos/{id}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri=\"/pedidos\"}[1m]))",
     "legendFormat": "pedidos"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "description": "duração média de requisições no ultimo minuto",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/pedidos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/pedidos/{id}\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"201\", uri=\"/pedidos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"201\", uri=\"/pedidos\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Max Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"$job\",status=~\"2.*\", uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {}
   ]
  },
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Heap Used",
   "type": "gauge",
   "description": "Memória Heap utilizada",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$job\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Utilização de CPU",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 46 },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$job\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{job=\"$job\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "Média de uso de CPU",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 46 },
   "targets": [
    {
     "expr": "system_load_average_1m{job=\"$job\"}",
     "legendFormat": "Load average [1m]"
    },
    {
     "expr": "system_cpu_count{job=\"$job\"}",
     "legendFormat": "CPU core size"
    }
   ]
  },
  {
   "title": "NonHeap Used ",
   "type": "gauge",
   "description": "Memómria nonheap utilizada",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$job\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}