apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:v3
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
        envFrom:
          - configMapRef:
              name: gateway
  selector:
    matchLabels:
      app: gateway
