apiVersion: v1
kind: ConfigMap
metadata:
  name: pagamentos
data:
  PORT: '8084'
  MYSQL_URL: jdbc:mysql://alurafood-bd:3306/alurafood-pagamento?createDatabaseIfNotExist=true
  EUREKA_URL: http://server:8081/eureka
  MS_PEDIDOS: http://pedidos:8083

