apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
spec:
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      containers:
      - name: pagamentos
        image: pagamentos:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8084
        envFrom:
          - configMapRef:
              name: pagamentos
