server:
  port: ${PORT:0}
spring:
  application:
    name: ms-pagamentos
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/alurafood-pagamento?createDatabaseIfNotExist=true}
    username: root
    password: root
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}
  instance:
    instance-id: ${spring.application.name}
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      confirmarPagamento:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s

ms-pedidos:
  url: ${MS_PEDIDOS:http://localhost:8082/ms-pedidos}
