server:
  port: 0
spring:
  application:
    name: ms-pagamentos
  datasource:
    url: 'jdbc:mysql://localhost:3306/alurafood-pagamento?createDatabaseIfNotExist=true'
    username: root
    password: root
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

ms-pedidos:
  url: ${MS_PEDIDOS:http://localhost:8082/ms-pedidos}
