apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
spec:
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
      - name: pedidos
        image: pedidos:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
        envFrom:
          - configMapRef:
              name: pedidos

