apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
spec:
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
      - name: pedidos
        image: pedidos:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
        envFrom:
          - configMapRef:
              name: pedidos
        env:
          - name: MYSQL_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: pedidos
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: pedidos
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: pedidos

