apiVersion: v1
kind: Secret
metadata:
  name: pedidos
type: Opaque
data:
  MYSQL_URL: amRiYzpteXNxbDovL2FsdXJhZm9vZC1iZDozMzA2L2FsdXJhZm9vZC1wZWRpZG8/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWU=
  MYSQL_USERNAME: cm9vdA==
  MYSQL_PASSWORD: cm9vdA==
