global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus-pedidos
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: ms-pedidos/actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - gateway:8082
